name = "unciv-server-cf"
main = "src/index.ts"
compatibility_date = "2025-12-27"

# Bind your KV namespace here. Replace the id with your KV namespace id.
[[kv_namespaces]]
binding = "UNCIV_KV"
id = "a5ec58f5b03e4e40b9093e8b24ff78fb"

# Example routes, account, etc. add as necessary for your project
